### ISSUE TITLE
Widget Aktualisierungen blockiert

### ISSUE THREAD

**Issue by Gurke258** [iobroker-community-adapters/ioBroker.vis-material-advanced#24]
Ich benutze folgende Version: 1.3.0

Hardwaresystem: | Pi4
-- | --
Arbeitsspeicher: | 4GB
Festplattenart: | SD-Karte
Betriebssystem: | Raspian
Node-Version: | 12.22.0
Nodejs-Version: | 12.22.0
NPM-Version: | 6.14.11

Aktuell bekomme ich folgende Fehlermeldung in der Console vom Cromium Browser:

`Error: Error: can't create states object for hm-rpc.0.LEQ1483852.1.TEMPERATURE(TypeError: Cannot read property 'toFixed' of undefined): "TypeError: Cannot read property 'toFixed' of undefined\n    at update (http://localhost:8082/vis/widgets/vis-material-advanced/js/vis-material-advanced.js:263:52)\n    at a.<anonymous> (http://localhost:8082/vis/widgets/vis-material-advanced/js/vis-material-advanced.js:270:17)\n    at a.t.dispatch (http://localhost:8082/vis/lib/js/can.custom.min.js:18:1252)\n    at Object.stop (http://localhost:8082/vis/lib/js/can.custom.min.js:44:451)\n    at a._setAttrs (http://localhost:8082/vis/lib/js/can.custom.min.js:48:4021)\n    at attr (http://localhost:8082/vis/lib/js/can.custom.min.js:48:1571)\n    at Object.updateState (http://localhost:8082/vis/js/vis.js:2899:29)\n    at http://localhost:8082/vis/js/vis.js:3456:21\n    at http://localhost:8082/vis/js/vis.js:3668:9"`

Ich vermute, dass das Problem vom Widget kommt.

**Comment by EdgarM73** [comment]
Hi @Gurke258 ,

du scheinst einen latest Stand installiert zu haben, und ich habe heute ein neues widget getestet .

Habe eben die 1.6 released, kannst es jetzt gerne versuchen oder morgen über das normale update machen.

grüße
E

**Comment by Gurke258** [comment]
Hey, 

ich habs aktualisiert aber leider immer noch das Problem.

Das Widget welches ich benutze ist das Kombi mit Temp & Humid :)

**Comment by EdgarM73** [comment]
Hi @Gurke258 ,

habe eben erst gesehen, dass du hm-rpc.0.LEQ1483852.1.TEMPERATURE als Objekt benutzt. 
Das gibt es meiner Mainung gar nicht, es sollte hm-rpc.0.LEQ1483852.1.ACTUAL_TEMPERATURE heissen.

In der Fehlermeldung steht ja auch undefined drin.

grüße
E

probier mal bitte

**Comment by Gurke258** [comment]
Guten morgen :)

Es gibt beide. Habe bei der Temperatur jetzt mal den aktual wert genommen. Habe auch gesehen das es bei der Luftfeuchtigkeit auch einen Actual Wert gibt, diesen kann ich leider nicht auswählen als Objekt.

![grafik](https://user-images.githubusercontent.com/36326543/113391408-c769b000-9393-11eb-821f-7490b487ac90.png)

![grafik](https://user-images.githubusercontent.com/36326543/113391599-10216900-9394-11eb-87ac-1159a173160c.png)

![grafik](https://user-images.githubusercontent.com/36326543/113391632-1e6f8500-9394-11eb-87be-e16d10fb8130.png)

**Comment by EdgarM73** [comment]
sind das Aliase?

**Comment by EdgarM73** [comment]
Kannst du bitte mal nachsehen, ob das Object wirklich eine Zahl ist?
unter (links ) Objekte -> rpc.0 -> LEQ... -> 2 -> ACTUAL_TEMPERATURE 
dort rechts auf den Stift-Button klicken und unter Allgemein -> Art == Zahl?

grüße
E

**Comment by Gurke258** [comment]
Hab ich gestern schon :) -> https://forum.iobroker.net/topic/12117/einige-vis-widgets-aktualisieren-sich-nicht/54?_=1617348900552

Ja sind beides Zahlen

![grafik](https://user-images.githubusercontent.com/36326543/113397086-c8530f80-939c-11eb-8db5-426f42ff4fa2.png)
![grafik](https://user-images.githubusercontent.com/36326543/113397136-db65df80-939c-11eb-983b-b1f9a65d3dcb.png)

**Comment by EdgarM73** [comment]
Ich habe heute morgen die 1.6.0 final released, ist aber noch nicht freigegeben.

Du könntest aber kurz auf Beta Channel setzen und nur meinen Adapter neu installieren.

Falls du es machst, bitte nicht vergessen es wieder zurückzusetzen.

1.3.0 ist schon sehr alt, auch wenn ich nicht sicher bin dass dein Problem wirklich gelöst wird dadurch.

Der Fehler bedeutet ( normalerweise ) dass entweder kein Wert ankommt oder eben keine Zahl.

grüße
E

**Comment by EdgarM73** [comment]
![image](https://user-images.githubusercontent.com/4679488/113398200-7f03bf80-939e-11eb-8110-e96ee5f7bdbc.png)

So sieht das Widget bei mir aus

![image](https://user-images.githubusercontent.com/4679488/113398330-b7a39900-939e-11eb-8f8a-9d71d1034a65.png)

und so mein Wandthermostat, allerdings der "alte", kein HMIP

grüße
E

**Comment by Gurke258** [comment]
Ich habe die 1.6.0 schon seit gestern abend drauf  :)

![grafik](https://user-images.githubusercontent.com/36326543/113398691-4b756500-939f-11eb-8630-2162c8d7108b.png)


Aber die Zuordnung ist bei mir die selbe ^^

![grafik](https://user-images.githubusercontent.com/36326543/113398766-63e57f80-939f-11eb-87bc-c9907d595710.png)

Das ist auch kein IP sondern ein normales über die CCU3 in den ioBroker rein :)

**Comment by EdgarM73** [comment]
Dann ist es noch seltsamer.

würden denn die "nromalen" widgets für Temperatur und Luftfeuchte funktionieren?

grüße
E

**Comment by EdgarM73** [comment]
übrigens , wenn du das Objekt nicht siehst, ich setze Filter auf Typen, klicke einfach im Auswahlfenster oben auf das x :

![image](https://user-images.githubusercontent.com/4679488/113400028-7496f500-93a1-11eb-8d23-105daf487075.png)

**Comment by Gurke258** [comment]
Ich hab es jetzt seit ca. 20 min mit den normalen, also beide einzeln laufen und habe noch kein Fehler... Scheint damit also zu gehen.
Habe auch jetzt nur von jedem eins genommen und nicht alle 5.

Das Kombi-Widget finde ich aber schöner, da es kompakter ist :)

**Comment by EdgarM73** [comment]
ich bin ehrlich gesagt ratlos,

das normale Temp widget und das kombinierte sind praktisch identisch:
  $div.find('.vma_value').html(state.toFixed(1) + type);

$div.find('.vma_value2_1').html(state.toFixed(1) + valtype1);
$div.find('.vma_value2_2').html(state2.toFixed(1) + valtype2);

wenn der Datenpunkt einmal geht und einmal nicht bin ich verwirrt.

Ich versuche nochmal drüberzuschauen.

**Comment by EdgarM73** [comment]
Könntest du mir das komplette Objekt exportieren und schicken?

Dann würde ich es einfach mal bei mir importieren und testen.

grüße
E

**Comment by Gurke258** [comment]
> 
> 
> Könntest du mir das komplette Objekt exportieren und schicken?
> 
> Dann würde ich es einfach mal bei mir importieren und testen.
> 
> grüße
> E

Habe dir ne Mail geschickt an die in Github hinterlegte Email-Adresse :)

**Comment by EdgarM73** [comment]
![image](https://user-images.githubusercontent.com/4679488/113409309-4ae5ca00-93b1-11eb-8d80-96c4282dcbdc.png)

Hat nicht weitergeholfen, bei mir funktionieren sie trotzdem :(

Ich werde mal überlegen wo das Problem sein könnte

grüße
E

**Comment by Gurke258** [comment]
Ja an sich funktioniert es ja auch wenn ich es einbinde. nur kommt irgendwann der Fehler in der Console von Chromium und dann geht kein einziges Widget mehr richtig.

**Comment by EdgarM73** [comment]
Kannst du mal im Log nach dem Datenpunkt filtern und schauen, ob es da Fehler gibt?

Anders kann ich es mir nicht erklären 

grüße
E

**Comment by Gurke258** [comment]
Tut mir leid, ich kann keine Auffälligkeiten in den Logs verzeichnen. Alles normal.

**Comment by EdgarM73** [comment]
hi @Gurke258 

würdest du nochmal den letzten Stand runterladen, also direkt von github über die Katze?

Ich habe ein Error Handling eingebaut, dann sollte wenigstens alles andere funktionieren.
grüße
E

**Comment by Gurke258** [comment]
Hab ich getan, leider keine Änderung bzw irgendwas ersichtliches außer der fehler in der Console.

**Comment by EdgarM73** [comment]
Es sollte aber nichts anderes mehr beeinflussen.

Kennst du dich aus mit Debuggen im Browser?

grüße

**Comment by Gurke258** [comment]
Naja auskennen ist wahrscheinlich etwas übertrieben gesagt aber ich hab hier und da mal rumgespielt
